SELECT MIN(numero) FROM simboli WHERE categoria_id = 6;
SELECT COUNT(*) FROM simboli WHERE categoria_id = 2;
SELECT MIN(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Hardware';
SELECT numero FROM simboli WHERE nome = 'Il Monitor';
SELECT numero FROM simboli WHERE nome = 'La Tastiera';
SELECT numero FROM simboli WHERE nome = 'Il Mouse';
SELECT COUNT(*) FROM simboli WHERE categoria_id = 9;
SELECT SUM(impatto) FROM eventi WHERE mese = 1;
SELECT MIN(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Storage';
SELECT COUNT(*) FROM simboli WHERE categoria_id = 5;
SELECT COUNT(*) FROM simboli WHERE categoria_id = 1;
SELECT MIN(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Sicurezza';
SELECT numero FROM simboli WHERE nome = 'Il Bug';
SELECT SUM(impatto) FROM eventi WHERE mese = 10;
SELECT SUM(impatto) FROM eventi WHERE mese = 7;
SELECT COUNT(*) FROM simboli WHERE livello = 1;
SELECT COUNT(*) FROM simboli WHERE livello = 4;
SELECT SUM(impatto) FROM eventi WHERE mese = 3;
SELECT MIN(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Database';
SELECT numero FROM simboli WHERE nome = 'La Tabella';
SELECT numero FROM simboli WHERE nome = 'Il Record';
SELECT numero FROM simboli WHERE nome = 'Il Campo';
SELECT SUM(impatto) FROM eventi WHERE mese = 4;
SELECT COUNT(*) FROM simboli WHERE livello = 3;
SELECT numero FROM simboli WHERE nome = 'Il JOIN';
SELECT COUNT(*) FROM simboli WHERE livello = 2;
SELECT numero FROM simboli WHERE nome = 'Il WHERE';
SELECT MAX(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Database';
SELECT SUM(impatto) FROM eventi WHERE mese = 12;
SELECT numero FROM simboli WHERE nome = 'La Funzione';
SELECT numero FROM simboli WHERE nome = 'Il Ciclo For';
SELECT numero FROM simboli WHERE nome = 'Il While';
SELECT SUM(impatto) FROM eventi WHERE mese = 11;
SELECT numero FROM simboli WHERE nome = 'La Stringa';
SELECT numero FROM simboli WHERE nome = 'Il Puntatore';
SELECT numero FROM simboli WHERE nome = 'La Classe';
SELECT numero FROM simboli WHERE nome = 'L\'Oggetto';
SELECT numero FROM simboli WHERE nome = 'Il Metodo';
SELECT numero FROM simboli WHERE nome = 'L\'Ereditarietà';
SELECT MAX(numero) FROM simboli WHERE categoria_id = 6;
SELECT MIN(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Web';
SELECT SUM(impatto) FROM eventi WHERE simbolo_numero = 13;
SELECT numero FROM simboli WHERE nome = 'JavaScript';
SELECT numero FROM simboli WHERE nome = 'Il Browser';
SELECT numero FROM simboli WHERE nome = 'Il Cookie';
SELECT numero FROM simboli WHERE nome = 'La Session';
SELECT numero FROM simboli WHERE nome = 'L\'API';
SELECT numero FROM simboli WHERE nome = 'Il JSON';
SELECT numero FROM simboli WHERE nome = 'Il Dominio';
SELECT MAX(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Web';
SELECT numero FROM simboli WHERE nome = 'Il Protocollo HTTP';
SELECT numero FROM simboli WHERE nome = 'Il DNS';
SELECT numero FROM simboli WHERE nome = 'L\'IP Address';
SELECT numero FROM simboli WHERE nome = 'La Subnet Mask';
SELECT numero FROM simboli WHERE nome = 'Il Gateway';
SELECT SUM(impatto) FROM eventi WHERE simbolo_numero = 68;
SELECT numero FROM simboli WHERE nome = 'La VLAN';
SELECT MAX(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Rete';
SELECT numero FROM simboli WHERE nome = 'La VPN';
SELECT numero FROM simboli WHERE nome = 'La Crittografia';
SELECT numero FROM simboli WHERE nome = 'L\'Hash';
SELECT numero FROM simboli WHERE nome = 'Il Certificato SSL';
SELECT numero FROM simboli WHERE nome = 'La Password';
SELECT numero FROM simboli WHERE nome = 'Il Token';
SELECT numero FROM simboli WHERE nome = 'L\'Autenticazione';
SELECT numero FROM simboli WHERE nome = 'Il Malware';
SELECT numero FROM simboli WHERE nome = 'Il Phishing';
SELECT MAX(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Sicurezza';
SELECT MIN(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Sistema';
SELECT numero FROM simboli WHERE nome = 'Il Kernel';
SELECT numero FROM simboli WHERE nome = 'Il Processo';
SELECT numero FROM simboli WHERE nome = 'Il Thread';
SELECT numero FROM simboli WHERE nome = 'La Memoria Virtuale';
SELECT numero FROM simboli WHERE nome = 'Il File System';
SELECT SUM(impatto) FROM eventi WHERE simbolo_numero = 15;
SELECT numero FROM simboli WHERE nome = 'Il BIOS';
SELECT numero FROM simboli WHERE nome = 'Il Boot';
SELECT numero FROM simboli WHERE nome = 'Il Terminale';
SELECT MAX(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Sistema';
SELECT numero FROM simboli WHERE nome = 'La GPU';
SELECT numero FROM simboli WHERE nome = 'La Scheda Madre';
SELECT numero FROM simboli WHERE nome = 'L\'Alimentatore';
SELECT numero FROM simboli WHERE nome = 'Il Case';
SELECT MAX(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Hardware';
SELECT numero FROM simboli WHERE nome = 'Il RAID';
SELECT numero FROM simboli WHERE nome = 'Il NAS';
SELECT numero FROM simboli WHERE nome = 'L\'Hard Disk';
SELECT MAX(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Storage';
SELECT MIN(numero) FROM simboli, categorie WHERE simboli.categoria_id = categorie.id AND categorie.nome = 'Software';
SELECT MAX(numero) FROM simboli;